#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageSaleMails
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GarageSale")]
	public partial class GarageSaleDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public GarageSaleDataContext() : 
				base(global::GarageSaleMails.Properties.Settings.Default.GarageSaleConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GarageSaleDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GarageSaleDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GarageSaleDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GarageSaleDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_whatMailToSent")]
		public ISingleResult<sp_whatMailToSentResult> sp_whatMailToSent()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_whatMailToSentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getTemplate")]
		public ISingleResult<sp_getTemplateResult> sp_getTemplate([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> templateid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), templateid);
			return ((ISingleResult<sp_getTemplateResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EmailDetails")]
		public ISingleResult<sp_EmailDetailsResult> sp_EmailDetails([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> itemid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), itemid);
			return ((ISingleResult<sp_EmailDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateEmailTrack")]
		public int sp_UpdateEmailTrack([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> itemid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string emailaddress)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), itemid, emailaddress);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class sp_whatMailToSentResult
	{
		
		private System.Nullable<int> _ItemID;
		
		private int _EmailNotificationID;
		
		private string _EmailAddress;
		
		private string _ItemName;
		
		public sp_whatMailToSentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemID", DbType="Int")]
		public System.Nullable<int> ItemID
		{
			get
			{
				return this._ItemID;
			}
			set
			{
				if ((this._ItemID != value))
				{
					this._ItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailNotificationID", DbType="Int NOT NULL")]
		public int EmailNotificationID
		{
			get
			{
				return this._EmailNotificationID;
			}
			set
			{
				if ((this._EmailNotificationID != value))
				{
					this._EmailNotificationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="VarChar(200)")]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this._EmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemName", DbType="VarChar(200)")]
		public string ItemName
		{
			get
			{
				return this._ItemName;
			}
			set
			{
				if ((this._ItemName != value))
				{
					this._ItemName = value;
				}
			}
		}
	}
	
	public partial class sp_getTemplateResult
	{
		
		private int _MailTemplateID;
		
		private string _TemplateText;
		
		public sp_getTemplateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailTemplateID", DbType="Int NOT NULL")]
		public int MailTemplateID
		{
			get
			{
				return this._MailTemplateID;
			}
			set
			{
				if ((this._MailTemplateID != value))
				{
					this._MailTemplateID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateText", DbType="VarChar(MAX)")]
		public string TemplateText
		{
			get
			{
				return this._TemplateText;
			}
			set
			{
				if ((this._TemplateText != value))
				{
					this._TemplateText = value;
				}
			}
		}
	}
	
	public partial class sp_EmailDetailsResult
	{
		
		private int _MessageID;
		
		private System.Nullable<int> _ItemID;
		
		private string _MessageText;
		
		private System.Nullable<int> _Seller;
		
		private System.DateTime _DateInserted;
		
		private System.Nullable<int> _MemberID;
		
		public sp_EmailDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageID", DbType="Int NOT NULL")]
		public int MessageID
		{
			get
			{
				return this._MessageID;
			}
			set
			{
				if ((this._MessageID != value))
				{
					this._MessageID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemID", DbType="Int")]
		public System.Nullable<int> ItemID
		{
			get
			{
				return this._ItemID;
			}
			set
			{
				if ((this._ItemID != value))
				{
					this._ItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageText", DbType="VarChar(MAX)")]
		public string MessageText
		{
			get
			{
				return this._MessageText;
			}
			set
			{
				if ((this._MessageText != value))
				{
					this._MessageText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seller", DbType="Int")]
		public System.Nullable<int> Seller
		{
			get
			{
				return this._Seller;
			}
			set
			{
				if ((this._Seller != value))
				{
					this._Seller = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateInserted", DbType="DateTime NOT NULL")]
		public System.DateTime DateInserted
		{
			get
			{
				return this._DateInserted;
			}
			set
			{
				if ((this._DateInserted != value))
				{
					this._DateInserted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberID", DbType="Int")]
		public System.Nullable<int> MemberID
		{
			get
			{
				return this._MemberID;
			}
			set
			{
				if ((this._MemberID != value))
				{
					this._MemberID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
